### ISSUE TITLE
Correcciones y consejos

### ISSUE THREAD

**Issue by Liluminalia** [Jesusnauta/W2ch3-Jesus-Enrique#6]
Buenas Jesús, a ver hay que revisar unas cuantas cosas:
- lo primero no podemos dejar el README prácticamente vacío, si alguien se fuera a descargar tu app, si ve este readme, no se la descargaría, tienes que explicar un poco de lo que va al menos, o mínimo el readmi del challenge, pero no asi medio vacío.
- ojo el editorconfig, le tienes tal y como viene, y al empezar el bootcamp se os paso un estándar para este documento, en discord e install config tienes un repo que paso Alejandro y al final del todo del readme tienes como debe quedar el editorconfig, si estuvieras en una empresa no puedes tener un formateo de código distinto al de tus compañeros, solo vas a conseguir asegurarte de que se generen conflictos, es importante!
- los test recuerda que llevan el Given, When, Then, un describe general con el Given, otro describe con el When, que recomendablemente (sobre todo para mas adelante) tengas que hacer muchos tests, te facilitara mucho encontrar el error, y por ultimo tantos tests como casos tenga la función, con el Then, no es en si que tengas que revisar que pasa con un dato u otro en la función, sino las posibilidades que tiene, por ejemplo si hay un if, que pasaría si se cumple y otro test con que pasaría si NO se cumple.
- ten en cuenta que los nombres de las ramas tienen que ser orientativos sobre lo que se esta haciendo, la rama que tiene un solo commit, que tiene de mensaje add husky files, la rama no se puede llamar feature/newbranch, un buen nombre podría ser por ejemplo: feature/initialConfig o feature/initial-config y ahí meter todas las instalaciones iniciales separándolas por varios commits, uno "Add husky files" (recuerda que la primera es con mayúscula), otro con "Add json config", y ya cuando subas esos tres por ejemplo, borras la rama y creas la de lo que vas a hacer, por ejemplo que vas a hacer la función del push, pues un buen nombre podría ser feature/pushFunction o feature/push-function. lo que no se puede hacer es que haya una rama que se llame "feature/testing" y el único commit que haya sea "add json config" ya que pierde el sentido y además que en ese commit en realidad haya cambios no solo del json config sino que hay parte de funciones, de testing, de todo un poco, tienes ahí un batiburrillo que necesitas corregir.

échale un ojo a todo esto y mucho animo! saludos!

**Comment by Jesusnauta** [comment]
Vale Sara, lo tengo en consideración. Muchas gracias.

**Comment by Liluminalia** [comment]
Genial entonces, cierro el issue
